### PR TITLE
Extraction class test

### PR DESCRIPTION
**Pull request by joelispartaglobal**
Created tests to see if data is extracted properly
a) Tested to see if lists start as 0 then become greater than 0 once get_data method is called
b) Tested to see if each list has the corresponding specified file type
c) Tested to see if the list is greater than 1

### CODE REVIEW

**Review by davidrichardharvey — CHANGES_REQUESTED** [review]
Make sure you aren't pushing .idea to the repo.  You might want to add it to your gitignore.

**Review by joelispartaglobal — COMMENTED** [review]
removed idea files

**Review by davidrichardharvey — APPROVED** [review]

**Review by CWeston98 — CHANGES_REQUESTED** [review]
Please explicitly check that a given file ends up in the correct list - i.e.  10603.json goes into the talent json list

**Review by CWeston98 — APPROVED** [review]
I've played around with some of the comments, but I haven't touched the code. It all looks good to me, I'm going to add it to the dev branch!

**Pull request merged**
